"""Regenerate the Python gRPC stubs in generated/ from proto/*.proto.

    python scripts/generate_proto.py
    python scripts/generate_proto.py --check    # fail if stubs are stale

grpc_tools emits flat imports ("import auction_pb2"), but this repo imports
the stubs as a package ("from generated import auction_pb2"), so they get
rewritten afterwards.

Stubs are committed so nobody needs protoc just to run a node.
"""

from __future__ import annotations

import argparse
import filecmp
import re
import subprocess
import sys
import tempfile
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
PROTO_DIR = REPO_ROOT / "proto"
OUT_DIR = REPO_ROOT / "generated"
PACKAGE = OUT_DIR.name

_INIT_DOC = '"""gRPC stubs generated by scripts/generate_proto.py. Do not edit by hand."""\n'


def _proto_files():
    files = sorted(PROTO_DIR.glob("*.proto"))
    if not files:
        raise SystemExit(f"no .proto files found in {PROTO_DIR}")
    return files


def _run_protoc(out_dir):
    out_dir.mkdir(parents=True, exist_ok=True)

    cmd = [
        sys.executable, "-m", "grpc_tools.protoc",
        f"--proto_path={PROTO_DIR}",
        f"--python_out={out_dir}",
        f"--grpc_python_out={out_dir}",
        *[str(p) for p in _proto_files()],
    ]

    proc = subprocess.run(cmd, capture_output=True, text=True)
    if proc.returncode != 0:
        sys.stderr.write(proc.stdout + proc.stderr)
        raise SystemExit(f"protoc failed with exit code {proc.returncode}")


def _rewrite_imports(out_dir):
    modules = sorted(p.stem for p in out_dir.glob("*_pb2.py"))
    if not modules:
        return

    pattern = re.compile(
        r"^import (%s) as (\w+)$" % "|".join(map(re.escape, modules)),
        re.MULTILINE,
    )

    for path in sorted(out_dir.glob("*_pb2*.py")):
        src = path.read_text()
        fixed = pattern.sub(rf"from {PACKAGE} import \1 as \2", src)
        if fixed != src:
            path.write_text(fixed)


def _generate_into(out_dir):
    _run_protoc(out_dir)
    _rewrite_imports(out_dir)

    # An existing file is left alone, and it is excluded from the staleness
    # check because the compiler does not produce it.
    init = out_dir / "__init__.py"
    if not init.exists():
        init.write_text(_INIT_DOC)


def _py_names(out_dir):
    return {p.name for p in out_dir.glob("*_pb2*.py")}


def check():
    with tempfile.TemporaryDirectory() as tmp:
        fresh = Path(tmp) / PACKAGE
        _generate_into(fresh)

        expected = _py_names(fresh)
        actual = _py_names(OUT_DIR)

        missing = expected - actual
        if missing:
            print(f"these are missing: {sorted(missing)}", file=sys.stderr)
            return 1

        extra = actual - expected
        if extra:
            print(f"these are unexpected: {sorted(extra)}", file=sys.stderr)
            return 1

        _, mismatch, errors = filecmp.cmpfiles(fresh, OUT_DIR, sorted(expected), shallow=False)
        if mismatch or errors:
            print(f"these differ from proto/: {sorted(mismatch + errors)}", file=sys.stderr)
            print("run: python scripts/generate_proto.py", file=sys.stderr)
            return 1

    print("generated/ is up to date with proto/")
    return 0


def generate():
    # Previous output is cleared first. Otherwise removing a definition would
    # leave a stub behind that still imports and hides the removal.
    if OUT_DIR.exists():
        for path in OUT_DIR.glob("*_pb2*.py"):
            path.unlink()
    else:
        OUT_DIR.mkdir(parents=True)

    _generate_into(OUT_DIR)

    for path in sorted(OUT_DIR.glob("*.py")):
        print(f"  {PACKAGE}/{path.name}")
    print(f"generated {len(_proto_files())} proto file(s) into {PACKAGE}/")
    return 0


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true",
                        help="verify committed stubs match proto/ (exit 1 if stale)")
    args = parser.parse_args(argv)

    return check() if args.check else generate()


if __name__ == "__main__":
    raise SystemExit(main())
